"""
Prompt builder — assembles all wizard answers + design knowledge +
local AI enhancement into a comprehensive, copy-paste-ready prompt.
"""
from shinka.wizard import WizardAnswers
from shinka.templates import (
    UNIVERSAL_RULES, SECTION_TEMPLATES, COMPONENT_PATTERNS,
)
from shinka.levels import LEVELS
from shinka.ui import console, animate_thinking, random_kaomoji


def build_prompt(answers: WizardAnswers, ai_enhance: bool = True) -> str:
    """Assemble the god-tier prompt from wizard answers."""
    sections = []

    # ── Header ───────────────────────────────────────────────────────────
    level = LEVELS[answers.level]
    sections.append(f"""# Frontend Design Prompt — Generated by Shinka (Level {answers.level}: {level['name']})

> This prompt was generated using the 7 Levels Frontend Design methodology.
> Paste this into Claude Code, Cursor, Windsurf, Copilot, or any AI code editor.
> Do NOT simplify or skip any instructions below — they are all intentional.""")

    # ── Role & Context ───────────────────────────────────────────────────
    sections.append("""---
## Role

You are a senior frontend developer and designer with 15+ years of experience
building award-winning websites. You have deep expertise in typography, color theory,
layout design, animation, accessibility, and responsive design. You care deeply
about craft and hate generic, template-looking designs. Every pixel matters to you.""")

    # ── Project Brief ────────────────────────────────────────────────────
    brief = f"""---
## Project Brief

- **Project Name:** {answers.project_name}
- **Description:** {answers.description}
- **Target Audience:** {answers.audience}
- **Primary Goal:** {answers.goal}
- **Page Sections:** {', '.join(answers.sections)}"""
    sections.append(brief)

    # ── Universal Anti-AI-Slop Rules ─────────────────────────────────────
    rules_text = "\n".join(f"- {rule}" for rule in UNIVERSAL_RULES)
    sections.append(f"""---
## Critical Design Rules (NEVER IGNORE)

{rules_text}""")

    # ── Visual Direction (Level 2+) ──────────────────────────────────────
    if answers.level >= 2 and answers.aesthetic_details:
        aesthetic = answers.aesthetic_details
        traits = "\n".join(f"- {t}" for t in aesthetic.get("key_traits", []))
        refs = ", ".join(aesthetic.get("references", []))

        vis = f"""---
## Visual Direction

- **Aesthetic:** {aesthetic.get('name', answers.aesthetic)}
- **Description:** {aesthetic.get('description', '')}
- **Reference Sites:** {refs}"""

        if answers.reference_sites:
            vis += f"\n- **Additional References:** {answers.reference_sites}"

        vis += f"""

### Key Visual Traits
{traits}"""

        # Font
        if answers.font_details:
            fd = answers.font_details
            vis += f"""

### Typography
- **Heading Font:** {fd['heading']}
- **Body Font:** {fd['body']}
- **Monospace Font:** {fd['mono']}
- **Pairing Note:** {fd['note']}
- Import from Google Fonts: `@import url('https://fonts.googleapis.com/css2?family={fd['heading'].replace(' ', '+')}:wght@400;500;600;700&family={fd['body'].replace(' ', '+')}:wght@300;400;500;600&display=swap');`"""

        # Color
        if answers.color_details:
            cd = answers.color_details
            vis += f"""

### Color System
```css
:root {{
  --color-bg: {cd['bg']};
  --color-surface: {cd['surface']};
  --color-border: {cd['border']};
  --color-text: {cd['text']};
  --color-muted: {cd['muted']};
  --color-accent: {cd['accent']};
  --color-accent-hover: {cd['accent_hover']};
  --gradient-primary: {cd['gradient']};
}}
```
- **Mood:** {cd['mood']}
- NEVER deviate from this palette. All colors must come from these variables."""

        # Animation
        if answers.animation_details:
            ad = answers.animation_details
            vis += f"""

### Animation & Motion
- **Intensity:** {answers.animation_intensity} — {ad['description']}"""
            if "rules" in ad:
                anim_rules = "\n".join(f"- {r}" for r in ad["rules"])
                vis += f"\n{anim_rules}"

        sections.append(vis)

    # ── Design Systems (Level 3+) ────────────────────────────────────────
    if answers.level >= 3:
        ds = f"""---
## Design System Specification

### Grid & Spacing
- **Grid System:** {answers.grid_system}
- Use spacing scale: 4px, 8px, 12px, 16px, 24px, 32px, 48px, 64px, 80px, 96px, 128px
- Section vertical padding: minimum 80px (desktop), 48px (mobile)
- Container max-width: 1200px with auto horizontal margin

### Typography Scale
- **Scale Ratio:** {answers.typography_scale_details.get('name', answers.typography_scale)}
- **Feel:** {answers.typography_scale_details.get('feel', '')}
- **Base size:** 16px"""

        ratio = answers.typography_scale_details.get("ratio", 1.25)
        sizes = {
            "xs": round(16 / ratio, 1),
            "sm": round(16 / (ratio ** 0.5), 1),
            "base": 16,
            "lg": round(16 * (ratio ** 0.5), 1),
            "xl": round(16 * ratio, 1),
            "2xl": round(16 * ratio**2, 1),
            "3xl": round(16 * ratio**3, 1),
            "4xl": round(16 * ratio**4, 1),
            "display": round(16 * ratio**5, 1),
        }
        size_vars = "\n".join(f"  --text-{k}: {v}px;" for k, v in sizes.items())
        ds += f"""
```css
:root {{
{size_vars}
}}
```

### Accessibility
- **Standard:** {answers.accessibility.upper().replace('_', ' ')}"""

        if answers.accessibility == "wcag_aa":
            ds += """
- Body text contrast ratio: ≥ 4.5:1
- Large text (18px+) contrast ratio: ≥ 3:1
- All interactive elements must have visible focus states
- Use semantic HTML elements (header, nav, main, section, article, footer)
- All images must have meaningful alt text
- Keyboard navigation must work for all interactive elements"""
        elif answers.accessibility == "wcag_aaa":
            ds += """
- Body text contrast ratio: ≥ 7:1
- Large text contrast ratio: ≥ 4.5:1
- All WCAG AA requirements plus enhanced contrast"""

        if answers.component_patterns:
            pattern_descriptions = "\n".join(
                f"- **{p}:** {COMPONENT_PATTERNS.get(p, 'Custom pattern')}"
                for p in answers.component_patterns
            )
            ds += f"""

### Component Patterns to Use
{pattern_descriptions}"""

        sections.append(ds)

    # ── Code References (Level 4+) ───────────────────────────────────────
    if answers.level >= 4:
        has_refs = any([answers.scraped_data, answers.code_snippets, answers.effects_to_replicate])
        if has_refs:
            cr = "---\n## Code References (Clone These Techniques)"

            if answers.scraped_data:
                cr += f"""

### Auto-Scraped from Live Sites
The following HTML/CSS was automatically extracted from real websites.
Study these patterns and replicate the exact techniques with our branding, copy, and content.
Do NOT copy text content — only replicate the design patterns, layouts, and effects.

{answers.scraped_data}"""

            if answers.code_snippets:
                cr += f"""

### Manual Reference Code
Study this code and replicate the exact techniques (but with our branding and content):

```
{answers.code_snippets}
```"""
            if answers.effects_to_replicate:
                cr += f"""

### Effects to Replicate
{answers.effects_to_replicate}"""
            sections.append(cr)

    # ── Custom Assets (Level 5+) ─────────────────────────────────────────
    if answers.level >= 5:
        has_custom = any([
            answers.custom_colors, answers.custom_fonts,
            answers.custom_interactions, answers.custom_assets_description,
        ])
        if has_custom:
            ca = "---\n## Custom Brand Assets"
            if answers.custom_colors:
                ca += f"\n\n### Brand Colors\nOverride the palette with: {answers.custom_colors}"
            if answers.custom_fonts:
                ca += f"\n\n### Custom Fonts\n{answers.custom_fonts}"
            if answers.custom_interactions:
                ca += f"\n\n### Micro-Interactions\n{answers.custom_interactions}"
            if answers.custom_assets_description:
                ca += f"\n\n### Custom Illustrations/SVGs\n{answers.custom_assets_description}"
            sections.append(ca)

    # ── Tech Stack (Level 6+) ────────────────────────────────────────────
    if answers.level >= 6:
        ts = answers.tech_stack_details
        tech = f"""---
## Technical Implementation

- **Framework:** {ts.get('name', answers.tech_stack)} — {ts.get('description', '')}
- **Animation Library:** {answers.animation_lib}
- **Smooth Scrolling:** {answers.smooth_scroll}
- **3D Elements:** {answers.three_d_elements}
- **Component Source:** {answers.component_source}"""
        sections.append(tech)

    # ── Frontier (Level 7) ───────────────────────────────────────────────
    if answers.level >= 7:
        frontier_parts = []
        if answers.webgl_requirements:
            frontier_parts.append(f"### WebGL Requirements\n{answers.webgl_requirements}")
        if answers.shader_effects:
            frontier_parts.append(f"### Shader Effects\n{answers.shader_effects}")
        if answers.data_viz:
            frontier_parts.append(f"### Data Visualizations\n{answers.data_viz}")
        if answers.procedural_animation:
            frontier_parts.append(f"### Procedural Animation\n{answers.procedural_animation}")
        if answers.performance_budget:
            frontier_parts.append(f"### Performance Budget\n{answers.performance_budget}")

        if frontier_parts:
            sections.append("---\n## Frontier Specifications\n\n" + "\n\n".join(frontier_parts))

    # ── Section-by-Section Instructions ──────────────────────────────────
    if answers.sections:
        sec_instructions = "---\n## Section-by-Section Build Instructions\n"
        for s in answers.sections:
            desc = SECTION_TEMPLATES.get(s, f"Custom section: {s}")
            sec_instructions += f"\n### {s.replace('_', ' ').title()}\n{desc}\n"
        sections.append(sec_instructions)

    # ── Final Assembly ───────────────────────────────────────────────────
    prompt = "\n\n".join(sections)

    # ── AI Enhancement ───────────────────────────────────────────────────
    if ai_enhance:
        prompt = _enhance_with_local_ai(prompt, answers)

    return prompt


def _enhance_with_local_ai(prompt: str, answers: WizardAnswers) -> str:
    """Use the local llama model to add extra creative suggestions."""
    from shinka.setup import chat_with_model

    console.print(
        f"\n  [magenta]⟳[/magenta] [cyan]Enhancing prompt with local AI...[/cyan]  "
        f"{random_kaomoji('thinking')}"
    )

    enhancement_request = f"""You are a senior UI/UX designer. Given this frontend design prompt for a project called "{answers.project_name}" ({answers.description}), suggest 3-5 specific, creative design enhancements that would make it stand out. Focus on:
1. A unique micro-animation idea for the hero section
2. A creative layout pattern for the features section
3. A subtle detail that would elevate the overall feel
4. One "wow factor" element that's uncommon

Keep each suggestion to 1-2 sentences. Be specific with CSS properties, values, and techniques. No generic advice.

The aesthetic is: {answers.aesthetic}
The color accent is: {answers.color_details.get('accent', 'cyan')}
"""

    try:
        ai_response = chat_with_model(enhancement_request)
        if ai_response and "[Local model unavailable" not in ai_response:
            prompt += f"""

---
## AI-Suggested Creative Enhancements

The following suggestions were generated by a local AI model to push the design further.
Apply these if they fit the overall vision:

{ai_response}"""
            console.print(f"  [green]✓[/green] [bold]AI enhancements added![/bold]  {random_kaomoji('done')}")
        else:
            console.print(f"  [yellow]⚠[/yellow] [dim]Local AI unavailable, skipping enhancement.[/dim]")
    except Exception:
        console.print(f"  [yellow]⚠[/yellow] [dim]AI enhancement skipped.[/dim]")

    return prompt
